server:
  port: 8762
spring:
  application:
    name: Discovery-Server

eureka:
  instance:
    appname: Eureka-Server-2

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-service-1.herokuapp.com:8761/eureka/,http://eureka-service-2.herokuapp.com:8762/eureka/